// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxLVP57bKPqmzRXpKs6IGd8pyIkkZyJhQ',
    appId: '1:647582114872:web:9b67ebc130c422547df2cd',
    messagingSenderId: '647582114872',
    projectId: 'safellink',
    authDomain: 'safellink.firebaseapp.com',
    storageBucket: 'safellink.firebasestorage.app',
    measurementId: 'G-KW44MR23NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2zNPiio0retbW4MexhiwnidWIsQTQQas',
    appId: '1:647582114872:android:919e615c48a84baa7df2cd',
    messagingSenderId: '647582114872',
    projectId: 'safellink',
    storageBucket: 'safellink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnS8tz_2GF62bq0FkQTdUlYCc7Y7WLIyQ',
    appId: '1:647582114872:ios:4d8fc4081e01418f7df2cd',
    messagingSenderId: '647582114872',
    projectId: 'safellink',
    storageBucket: 'safellink.firebasestorage.app',
    iosBundleId: 'com.example.clinte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnS8tz_2GF62bq0FkQTdUlYCc7Y7WLIyQ',
    appId: '1:647582114872:ios:4d8fc4081e01418f7df2cd',
    messagingSenderId: '647582114872',
    projectId: 'safellink',
    storageBucket: 'safellink.firebasestorage.app',
    iosBundleId: 'com.example.clinte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxLVP57bKPqmzRXpKs6IGd8pyIkkZyJhQ',
    appId: '1:647582114872:web:9b573d6209718ef97df2cd',
    messagingSenderId: '647582114872',
    projectId: 'safellink',
    authDomain: 'safellink.firebaseapp.com',
    storageBucket: 'safellink.firebasestorage.app',
    measurementId: 'G-N0V350ST9M',
  );
}
